#!/usr/bin/env bash
set -eux
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install jupyterlab-plotly@4.8.1
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install @jupyter-widgets/jupyterlab-manager plotlywidget@4.8.1
# jupyter labextension install jupyterlab-drawio
jupyter labextension list
