#!/usr/bin/env bash
set -eux
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install jupyterlab-plotly@5.0.0
jupyter labextension install @jupyter-widgets/jupyterlab-manager
# jupyter labextension install jupyterlab-drawio
jupyter labextension list
